//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Swift Xcode Templates.
//

import UIKit

class ___VARIABLE_viewModelName___: ___VARIABLE_interactorIOName___ {
    // MARK: - Properties
    // MARK: InteractorIO
    var input: ___VARIABLE_interactorInputName___ { return self }
    var output: ___VARIABLE_interactorOutputName___ { return self }
    
    // MARK: - Initialization
    init() {
        
    }
}


// MARK: - ___VARIABLE_interactorInputName___
extension ___VARIABLE_viewModelName___: ___VARIABLE_interactorInputName___ {

}


// MARK: - ___VARIABLE_interactorOutputName___
extension ___VARIABLE_viewModelName___: ___VARIABLE_interactorOutputName___ {
    
}
