//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates.
//

import UIKit

class ___VARIABLE_viewControllerName___: UITableViewController {
    
    // MARK: - Properties
    // MARK: Private
    fileprivate var viewModel: ___VARIABLE_interactorInputName___?
    
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false
        
        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: Configure
    func configure(_ interactorInput: ___VARIABLE_interactorInputName___) {
        viewModel = interactorInput
        viewModel?.delegate = self
    }
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
        // Please define identifier of prefix use to be `Show`.
        // ex. ShowProductList etc.
    }
}


// MARK: - UITableViewDataSource
extension ___VARIABLE_viewControllerName___ {
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        // #warning Incomplete implementation, return the number of sections
        return 0
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete implementation, return the number of rows
        return 0
    }
}


// MARK: - ___VARIABLE_interactorOutputName___
extension ___VARIABLE_viewControllerName___: ___VARIABLE_interactorOutputName___ {

}
