//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates.
//

import UIKit

class ___VARIABLE_viewModelName___{
    
    // MARK: - Properties
    // MARK: Events
    weak var delegate: ___VARIABLE_interactorOutputName___?
  
    //MARK: - Lifecycle
    init() {
        
    }
}


// MARK: - ___VARIABLE_interactorInputName___
extension ___VARIABLE_viewModelName___: ___VARIABLE_interactorInputName___ {

}
