//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Swift Xcode Templates.
//

import Foundation

// MARK: - InteractorIO
protocol ___VARIABLE_interactorIOName___ {
    var input: ___VARIABLE_interactorInputName___ { get }
    var output: ___VARIABLE_interactorOutputName___ { get }
}


// MARK: - Input
protocol ___VARIABLE_interactorInputName___: class {
    /// Properties
    
    /// Methods
}


// MARK: - Output
protocol ___VARIABLE_interactorOutputName___: class {
    /// Properties
    
    /// Methods
}

