//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates.
//

import Foundation

// MARK: - Input
protocol ___VARIABLE_interactorInputName___ {
    /// Events
    weak var delegate: ___VARIABLE_interactorOutputName___? { get set }
    
    /// Methods
}


// MARK: - Output
protocol ___VARIABLE_interactorOutputName___: class {
    /// Methods
}
