//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates.
//

import UIKit

class ___VARIABLE_viewControllerName___: UIViewController {
    
    // MARK: - Properties
    // MARK: Private
    fileprivate var viewModel: ___VARIABLE_interactorInputName___?

    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
  
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: Configure
    func configure(_ interactorInput: ___VARIABLE_interactorInputName___) {
        viewModel = interactorInput
        viewModel?.delegate = self
    }
    
    // MARK: Setup
    private func setupUI() {
        
    }
    
    // MARK: - Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
        // Please define identifier of prefix use to be `Show`.
        // ex. ShowProductList etc.
    }
}


// MARK: - ___VARIABLE_interactorOutputName___
extension ___VARIABLE_viewControllerName___: ___VARIABLE_interactorOutputName___ {
    
}
